spring.application.name=ai-bot-backend

springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true

logging.level.root=INFO
logging.level.mk.ukim.finki.aibotbackend=DEBUG
logging.level.org.springframework=WARN

logging.file.name=logs/app.log
logging.logback.rollingpolicy.max-file-size=10MB
logging.logback.rollingpolicy.max-history=30

logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

jwt.secret=${JWT_SECRET_KEY}
jwt.expiration=864000000
jwt.header=Authorization
jwt.token-prefix=Bearer

vezilka.base-url=https://doniraj.vezilka.ai
vezilka.api-key=${VEZILKA_API_KEY:}

bot.max-steps-per-target=50
bot.headless=false

spring.profiles.active=dev

openrouter.base-url=https://openrouter.ai/api/v1
openrouter.api-key=${OPENROUTER_API_KEY}
openrouter.model=poolside/laguna-m.1:free
openrouter.fallback-models=nvidia/nemotron-3-ultra-550b-a55b:free,cohere/north-mini-code:free,poolside/laguna-xs-2.1:free
linkedin.username=${LINKEDIN_USERNAME}
linkedin.password=${LINKEDIN_PASSWORD}